import { type NextPage } from "next";
import Head from "next/head";
import { SideBar } from "../components/SideBar";
import { Layout } from "~/components/layout";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row">
        <SideBar />
        <Layout>
        </Layout>
      </main>

    </>
  );
};

export default Home;
